# -*- mode: python -*-
Import("env")

env = env.Clone()

env.Library(
    target='key',
    source=[
        'key.cpp'
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/util/secure_zero_memory'
    ],
)

env.Library(
    target='encryption_options',
    source=[
        'encryption_options.cpp',
    ],
    LIBDEPS=[
    ],
)

env.Library(
    target='encryption_vault',
    source=[
    	'encryption_vault.cpp',
    ],
    SYSLIBDEPS=[
        'winhttp' if env.TargetOSIs('windows') else 'curl',
    ],
)

env.InjectThirdParty(libraries=['kmippp'])

env.Library(
    target='encryption_kmip',
    source=[
    	'encryption_kmip.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/third_party/shim_kmippp',
    ],
)
