# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='telemetry',
    source=[
        'telemetry_parameter.cpp',
        'telemetry_parameter.idl',
        'telemetry_thread.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        #'$BUILD_DIR/mongo/idl/idl_parser',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/server_base',
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/mongo/util/background_job',
    ],
)

