# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='telemetry_base',
    source=[
        'telemetry_parameter.cpp',
        'telemetry_parameter.idl',
        'telemetry_thread_base.cpp',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/server_base',
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/mongo/util/background_job',
    ],
)

env.Library(
    target='telemetry_d',
    source=[
        'telemetry_thread_d.cpp',
    ],
    LIBDEPS=[
        'telemetry_base',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/repl/storage_interface',
        '$BUILD_DIR/mongo/s/coreshard',
        '$BUILD_DIR/mongo/util/background_job',
    ],
)

env.Library(
    target='telemetry_s',
    source=[
        'telemetry_thread_s.cpp'
    ],
    LIBDEPS=[
        'telemetry_base',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/s/coreshard',
        '$BUILD_DIR/mongo/util/background_job',
    ],
)
