#!/bin/bash
# postinst script for Percona Server for MongoDB sharded cluster query router
#
# see: dh_installdeb(1)


set -e

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi

if [ -d /usr/local/percona/telemetry ]; then
    mkdir -p /usr/local/percona/telemetry/psmdb
    chown mongod:percona-telemetry /usr/local/percona/telemetry/psmdb
    chmod 775 /usr/local/percona/telemetry/psmdb
    chmod g+s /usr/local/percona/telemetry/psmdb
    chmod u+s /usr/local/percona/telemetry/psmdb
fi

exit 0
