Import("env")

env = env.Clone()

env.SConscript(
    dirs=[
        'mongobridge_tool',
        'mongo_tidy_checks',
        'workload_simulation',
    ],
    exports=[
        'env',
    ],
)

perconadecrypt = env.Program(
    target='perconadecrypt',
    source=[
        'perconadecrypt.cpp',
        'perconadecrypt_options.cpp',
        'perconadecrypt_options.idl',
        'perconadecrypt_options_init.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/encryption/encryption_options',
        '$BUILD_DIR/mongo/db/encryption/key_management',
        '$BUILD_DIR/mongo/util/options_parser/options_parser_init',
    ],
    AIB_COMPONENT='perconadecrypt',
)

